import { Brand, Product, SimplifiedBatch } from '@/types/catalog';

export const mockBrands: Brand[] = [
  {
    id: 'brand-001',
    name: 'Château Mukhrani',
    description: 'Historic Georgian winery established in the 19th century, blending tradition with modern winemaking.',
    logo: '/placeholder.svg',
    website: 'https://chateaumukhrani.com',
    contactEmail: 'info@chateaumukhrani.com',
    contactPhone: '+995 555 123 456',
    address: 'Mukhrani Village, Mtskheta-Mtianeti',
    country: 'GE',
    region: 'Kakheti',
    foundedYear: 1878,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'brand-002',
    name: 'Pheasant\'s Tears',
    description: 'Natural wine producer focusing on ancient Georgian grape varieties and traditional qvevri methods.',
    logo: '/placeholder.svg',
    website: 'https://pheasantstears.com',
    contactEmail: 'wine@pheasantstears.com',
    contactPhone: '+995 555 789 012',
    address: 'Signagi, Kakheti',
    country: 'GE',
    region: 'Kakheti',
    foundedYear: 2007,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-07-15'),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    brandId: 'brand-001',
    name: 'Saperavi Reserve',
    category: 'Wine',
    grapeVariety: ['Saperavi'],
    docStatus: 'PDO',
    description: 'Full-bodied dry red wine with intense color and complex flavors of dark berries, spices, and subtle oak notes.',
    characteristics: 'Deep ruby color with purple hues. Aromas of blackberry, cherry, and violet with hints of spice and chocolate.',
    servingRecommendation: 'Serve at 16-18°C. Decant 1 hour before serving.',
    agingPotentialMin: 5,
    agingPotentialMax: 15,
    foodPairings: ['Grilled lamb', 'Beef stew', 'Aged cheeses', 'Dark chocolate'],
    notRecommendedWith: 'Delicate fish dishes, light salads',
    mainPhoto: '/placeholder.svg',
    galleryPhotos: [],
    productStory: 'Crafted from hand-selected Saperavi grapes grown in our historic vineyards.',
    traditionalMethods: 'Aged in Georgian oak barrels for 18 months.',
    awards: [
      { name: 'Decanter World Wine Awards', year: 2023, medalType: 'gold' },
      { name: 'International Wine Challenge', year: 2022, medalType: 'silver' },
    ],
    qrCodeSize: 'medium',
    qrCodeStyle: 'branded',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-08-10'),
  },
  {
    id: 'prod-002',
    brandId: 'brand-001',
    name: 'Rkatsiteli Qvevri',
    category: 'Wine',
    grapeVariety: ['Rkatsiteli'],
    docStatus: 'PDO',
    description: 'Amber wine made in traditional qvevri, offering unique texture and complex flavors.',
    characteristics: 'Golden amber color with aromas of dried apricot, honey, and herbal notes.',
    servingRecommendation: 'Serve at 12-14°C.',
    agingPotentialMin: 3,
    agingPotentialMax: 10,
    foodPairings: ['Roasted poultry', 'Spiced dishes', 'Hard cheeses'],
    mainPhoto: '/placeholder.svg',
    galleryPhotos: [],
    productStory: 'Made using 8,000-year-old Georgian winemaking tradition.',
    traditionalMethods: 'Fermented and aged in qvevri for 6 months on skins.',
    qrCodeSize: 'medium',
    qrCodeStyle: 'standard',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'prod-003',
    brandId: 'brand-002',
    name: 'Mtsvane Natural',
    category: 'Wine',
    grapeVariety: ['Mtsvane'],
    docStatus: 'PGI',
    description: 'Natural wine with minimal intervention, expressing pure terroir character.',
    characteristics: 'Pale gold with green reflections. Fresh and mineral with citrus and floral notes.',
    servingRecommendation: 'Serve chilled at 10-12°C.',
    agingPotentialMin: 2,
    agingPotentialMax: 5,
    foodPairings: ['Fresh seafood', 'Light salads', 'Soft cheeses'],
    mainPhoto: '/placeholder.svg',
    galleryPhotos: [],
    productStory: 'Expression of Kakheti terroir through natural winemaking.',
    qrCodeSize: 'small',
    qrCodeStyle: 'standard',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-09-01'),
  },
];

export const mockSimplifiedBatches: SimplifiedBatch[] = [
  {
    id: 'batch-001',
    productId: 'prod-001',
    vintageYear: '2022',
    numberOfUnits: 5000,
    productionDate: new Date('2022-09-15'),
    bottlingDate: new Date('2024-03-20'),
    fermentationDuration: 18,
    fermentationUnit: 'months',
    traditionalMethod: true,
    organicCertification: false,
    qualityGrade: 'reserve',
    batchNotes: 'Exceptional harvest year with ideal weather conditions.',
    status: 'active',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'batch-002',
    productId: 'prod-002',
    vintageYear: '2023',
    numberOfUnits: 3000,
    productionDate: new Date('2023-09-20'),
    bottlingDate: new Date('2024-05-15'),
    fermentationDuration: 6,
    fermentationUnit: 'months',
    traditionalMethod: true,
    organicCertification: true,
    qualityGrade: 'premium',
    status: 'active',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-05-15'),
  },
];
