export const mockBatch = {
  id: 'AUTH-2024-001',
  productName: 'Saperavi Reserve',
  vintageYear: '2021',
  category: 'Wine',
  grapeVariety: ['Saperavi'],
  numberOfUnits: 5000,
  region: 'Kakheti',
  docStatus: 'PDO',
  productionDate: new Date('2021-09-15'),
  bottlingDate: new Date('2023-06-20'),
  fermentationDuration: 6,
  fermentationUnit: 'months',
  traditionalMethod: true,
  organicCertification: true,
  description: 'A bold, full-bodied red wine made from 100% Saperavi grapes grown in the heart of Kakheti. Aged in traditional Georgian Qvevri for six months, this reserve showcases the authentic character of Georgian winemaking.',
  characteristics: 'Deep ruby color with purple hues. Intense aromas of blackberry, plum, and dark cherry, complemented by notes of vanilla and spice. Full-bodied with firm tannins and a long, elegant finish.',
  servingRecommendation: 'Serve at 16-18°C in a large burgundy glass. Decant for 30 minutes before serving to allow the wine to breathe.',
  agingPotentialMin: 5,
  agingPotentialMax: 15,
  foodPairings: ['Beef', 'Lamb', 'Game', 'Hard Cheese', 'Grilled Vegetables'],
  mainPhoto: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
  galleryPhotos: [
    'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
    'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800',
    'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800',
  ],
  videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  companyHistory: 'Founded in 1847, our family winery has been producing exceptional Georgian wines for five generations. Located in the Kakheti region, we maintain the traditional methods passed down through centuries while embracing modern quality standards.',
  productStory: 'This Saperavi Reserve represents our commitment to preserving Georgian winemaking heritage. Each grape is hand-selected from our 50-year-old vines, ensuring only the finest fruit makes it into the bottle. The wine is fermented and aged in traditional Qvevri buried underground, a method recognized by UNESCO as part of Georgian cultural heritage.',
  traditionalMethods: 'Fermented in traditional Georgian Qvevri - large clay vessels buried underground. This ancient method, dating back 8,000 years, imparts unique characteristics and is recognized by UNESCO as Intangible Cultural Heritage.',
  awards: [
    { name: 'Gold Medal - International Wine Challenge', year: 2023, medalType: 'gold' as const },
    { name: 'Best Georgian Red - Decanter Awards', year: 2023, medalType: 'gold' as const },
    { name: 'Silver Medal - Berlin Wine Trophy', year: 2022, medalType: 'silver' as const },
  ],
  companyName: 'Kakheti Wine Estate',
  address: '123 Vineyard Road, Telavi, Kakheti Region, Georgia',
  phone: '+995 555 123 456',
  email: 'contact@kakhetiwine.ge',
  website: 'https://kakhetiwine.ge',
  socialMedia: '@kakhetiwine',
  status: 'active' as const,
  qr1Scans: 2450,
  qr2Verifications: 1120,
  conversionRate: 45.7,
  rating: 4.7,
  reviewCount: 124,
};

export const mockReviews = [
  {
    id: '1',
    author: 'Giorgi M.',
    rating: 5,
    date: '2024-01-15',
    comment: 'Exceptional wine! The traditional Qvevri method really shows in the depth of flavor. Perfect with grilled lamb.',
  },
  {
    id: '2',
    author: 'Sarah L.',
    rating: 5,
    date: '2024-01-10',
    comment: 'Discovered this during my trip to Georgia. Absolutely loved it. The bold flavors and smooth finish make it perfect for special occasions.',
  },
  {
    id: '3',
    author: 'David K.',
    rating: 4,
    date: '2024-01-05',
    comment: 'Great wine with authentic Georgian character. A bit tannic for my taste but excellent quality overall.',
  },
];

export const mockSimilarProducts = [
  {
    id: 'AUTH-2024-002',
    name: 'Rkatsiteli Classic',
    vintageYear: '2022',
    thumbnail: 'https://images.unsplash.com/photo-1504279577054-acfeccf8fc52?w=400',
  },
  {
    id: 'AUTH-2024-003',
    name: 'Saperavi Rosé',
    vintageYear: '2023',
    thumbnail: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
  },
  {
    id: 'AUTH-2024-004',
    name: 'Kisi Amber',
    vintageYear: '2022',
    thumbnail: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=400',
  },
];
